/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

public class App {
    
    public static void main(String[] args) {

        Personagem personagem1 = new Personagem();

        personagem1.nivelinicial(0);
        personagem1.aumentarNivel();
        personagem1.aumentarNivel();

        IO.println(personagem1.nivelAtual());
        personagem1.forcaInicial(0);
        personagem1.aumentarforca();

        IO.println(personagem1.forcaAtual());

    }
      
}
