/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

public class App {
   

    public static void main(String[] args) {
        
        Batedeira batedeira1 = new Batedeira();

        System.out.println("Etapas para bater massa de pão em uma batedeira de pequeno porte \n");

        batedeira1.abrirTampa();
        System.out.println(batedeira1.selecionarPa());
        batedeira1.encaixarBacia();
        batedeira1.fecharTampa();
        batedeira1.ligarBatedeira();
    }
}
