/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;


public class App {
 
    public static void main(String[] args) {
        
        String primeiro = args[0];
        int segundo = Integer.parseInt(args[1]);
        int terceiro = Integer.parseInt(args[2]);
        String imagem = "*";

        if(primeiro.equals("triangulo")){
            for(int i = 0; i < segundo; i++){
                System.out.println(imagem);
                imagem += "*";
            }
        
        }   else if(primeiro.equals("losango")){ 

                for(int j = 0; j < segundo; j++){
                    
                    
                }
            }   else if(primeiro.equals("retangulo")){
                    for(int k = 0; k < segundo; k++ ){
                        System.out.print(imagem);
                        for(int l = 0; l < terceiro; l++){
                            System.out.println(imagem);
                        }
                    }

                }
                System.out.println();

        

    }
}
