/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

import java.util.Random;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Random r = new Random();
        int contador = 0;
        int numero;

        System.out.println("Entre com um número entre 1 e 100");
        numero = sc.nextInt();
        int aleatorio = r.nextInt(101);

        while(numero != aleatorio){

            if(numero > aleatorio){
                System.out.println("O número informado é maior que o sorteado");
            } else {
                System.out.println("O número informado é menor que o sorteado");               
            }
            numero = sc.nextInt();

            contador += 1;
        }
        System.out.println("Parabéns, você acertou! \n" + "tentativas: " + contador);               
        sc.close();
    }
}
