/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner sc = new Scanner(System.in);

        System.out.println("Ente com seu nome: ");
        String nome = sc.next();

        System.out.println("Ola " + nome);

        int contador = 0;

        for(String aux: args){

            if(aux.equals("POO")){
                System.out.println("Acertou!");
            } else{
                contador++;
            }
            System.out.println("Total de argumentos diferentes de POO" + contador);
        }

        // Incluir buidOutputCleanup

    }
}
