/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

public class App {

    public static void main(String[] args) {

        Contador contador1 = new Contador();

        contador1.atribuirValor(10);
        contador1.incrementarValor();

        IO.println(contador1.obterValorAtual());

    }
}