/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int dia;
        String mes, estacao;

        System.out.println("Entre com um número inteiro entre 1 e 31 representando o dia do mês: ");
        dia = sc.nextInt();

        System.out.println("Entre com o nome do mês: ");
        mes = sc.next();

             estacao = switch (mes) {
                case "dezembro", "janeiro", "fevereiro", "março" -> "Verão";
                case "setembro", "outubro", "novembro", "dezembro" -> "Primavera";
                case "junho", "julho", "agosto", "setembro" -> "Inverno";
                case "março","abriu","maio","junho" -> "Outono";
                default -> "";
            };

    }
}


