/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
   

    public static void main(String[] args) {

        Carro fusca = new Carro();

        fusca.acelerar(70);
        fusca.acelerar(40);


        IO.println(fusca.obterVelocidadeAtual());

    }
}
